# Generated by Django 5.0.6 on 2024-07-04 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_issue',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
